const products = [
  {id:1,name:'Lenovo IdeaPad Slim 3',category:'Laptops',specs:'Intel Core i5 · 8 GB · SSD 512 GB',price:329900,stock:12,type:'laptop',badge:'Para tu día a día',color:'#93ac9c'},
  {id:2,name:'Logitech MX Master 3S',category:'Accesorios',specs:'Inalámbrico · Bluetooth · Grafito',price:64900,stock:24,type:'mouse',badge:'Favorito',color:'#424b45'},
  {id:3,name:'Samsung Essential 24”',category:'Monitores',specs:'Full HD · IPS · 75 Hz',price:89900,stock:8,type:'monitor',badge:'Más espacio para crear',color:'#b4c2aa'},
  {id:4,name:'JBL Tune 520BT',category:'Audio',specs:'Bluetooth · Hasta 57 h de batería',price:29900,stock:18,type:'headphones',badge:'Tu música, contigo',color:'#424b40'},
  {id:5,name:'HP Pavilion 15',category:'Laptops',specs:'AMD Ryzen 5 · 16 GB · SSD 512 GB',price:419900,stock:6,type:'laptop',badge:'Potencia creativa',color:'#b1afcb'},
  {id:6,name:'Logitech Pebble M350',category:'Accesorios',specs:'Compacto · Inalámbrico · Silencioso',price:16900,stock:30,type:'mouse',badge:'Esenciales',color:'#bec6b7'},
  {id:7,name:'LG UltraWide 29”',category:'Monitores',specs:'UltraWide Full HD · IPS · 100 Hz',price:159900,stock:5,type:'monitor',badge:'Amplía tu perspectiva',color:'#9eafc0'},
  {id:8,name:'Sony WH-CH520',category:'Audio',specs:'Bluetooth · Hasta 50 h de batería',price:34900,stock:14,type:'headphones',badge:'Sonido sin cables',color:'#d4c6ae'}
];
const money = value => new Intl.NumberFormat('es-CR',{style:'currency',currency:'CRC',maximumFractionDigits:0}).format(value);
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let cart=read('nexo-cart',[]);cart=Array.isArray(cart)?cart.filter(i=>products.some(p=>p.id===i.id)&&Number.isInteger(i.qty)&&i.qty>0).map(i=>({id:i.id,qty:Math.min(i.qty,products.find(p=>p.id===i.id).stock)})):[];
let orders=read('nexo-orders',[]);if(!Array.isArray(orders))orders=[];
let category='Todos',toastTimer;
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{notify('El navegador no permite guardar los datos.');return false}}
function notify(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function art(p){const c=p.color;let shape='';if(p.type==='laptop'||p.type==='monitor'){shape=`<rect x="30" y="28" width="180" height="118" rx="6" fill="#37443c"/><rect x="36" y="34" width="168" height="105" rx="2" fill="${c}"/><path d="M36 118 Q95 24 150 86 T204 57 V139 H36Z" fill="#e3e9d6" opacity=".8"/><path d="M36 132 Q118 70 204 112 V139 H36Z" fill="#668878"/>`+(p.type==='laptop'?'<path d="M30 146 H210 L232 160 Q236 166 226 167 H14 Q4 166 8 160Z" fill="#adb6ac"/><path d="M97 147 H143 L148 153 H92Z" fill="#7c887d"/>':'<path d="M111 146 H129 L134 169 H106Z" fill="#929d94"/><rect x="85" y="168" width="70" height="6" rx="3" fill="#6f7b72"/>')}
if(p.type==='mouse')shape=`<path d="M80 153 Q57 143 67 90 Q72 42 113 34 Q155 28 168 75 L177 128 Q180 159 145 170 Q101 181 80 153Z" fill="${c}"/><path d="M115 37 Q105 66 112 96 L170 102" fill="none" stroke="#ffffff" stroke-opacity=".2" stroke-width="2"/><rect x="112" y="57" width="9" height="26" rx="4" fill="#202e26"/><path d="M78 98 Q89 126 83 148" fill="none" stroke="#ffffff" stroke-opacity=".13" stroke-width="3"/>`;
if(p.type==='headphones')shape=`<path d="M61 119 V86 C61 11 180 11 180 86 V119" fill="none" stroke="${c}" stroke-width="20"/><path d="M64 79 C67 20 175 20 177 79" fill="none" stroke="#ffffff" stroke-opacity=".2" stroke-width="5"/><rect x="47" y="91" width="38" height="71" rx="17" transform="rotate(-12 66 126)" fill="${c}"/><rect x="157" y="91" width="38" height="71" rx="17" transform="rotate(12 176 126)" fill="${c}"/><rect x="74" y="99" width="13" height="57" rx="6" fill="#263b30"/><rect x="155" y="99" width="13" height="57" rx="6" fill="#263b30"/>`;
return `<svg class="device" viewBox="0 0 240 200" role="img" aria-label="Ilustración de ${p.name}">${shape}</svg>`}
function render(){document.querySelector('.filters').innerHTML=['Todos','Laptops','Monitores','Accesorios','Audio'].map(c=>`<button class="${category===c?'active':''}" aria-pressed="${category===c}" data-category="${c}">${c}</button>`).join('');const q=document.querySelector('#search').value.toLocaleLowerCase();const list=products.filter(p=>(category==='Todos'||p.category===category)&&`${p.name} ${p.specs}`.toLocaleLowerCase().includes(q));const sort=document.querySelector('#sort').value;if(sort!=='featured')list.sort((a,b)=>sort==='asc'?a.price-b.price:b.price-a.price);document.querySelector('#result-count').textContent=`${list.length} productos`;document.querySelector('#products').innerHTML=list.map(p=>`<article class="product"><div class="product-art"><span class="badge">${p.badge}</span>${art(p)}</div><div class="product-category">${p.category}</div><h3>${p.name}</h3><p class="specs">${p.specs}</p><div class="product-bottom"><div><div class="price">${money(p.price)}</div><div class="stock">● ${p.stock} disponibles · demo</div></div><button class="add" data-add="${p.id}" aria-label="Agregar ${p.name}">+</button></div></article>`).join('')||'<div class="empty">No encontramos productos. Prueba otra búsqueda o categoría.</div>'}
const total=()=>cart.reduce((sum,i)=>sum+products.find(p=>p.id===i.id).price*i.qty,0);
function updateCart(){document.querySelector('#cart-count').textContent=cart.reduce((n,i)=>n+i.qty,0);document.querySelector('#cart-items').innerHTML=cart.map(i=>{const p=products.find(p=>p.id===i.id);return `<div class="cart-row"><div><h3>${p.name}</h3><small>${money(p.price)}</small></div><div class="qty"><button data-change="${i.id}" data-delta="-1" aria-label="Reducir cantidad de ${p.name}">−</button><span>${i.qty}</span><button data-change="${i.id}" data-delta="1" aria-label="Aumentar cantidad de ${p.name}">+</button></div><button class="remove" data-remove="${i.id}">Quitar</button></div>`}).join('')||'<div class="empty">Tu bolsa está esperando buenas ideas.<br>Explora el catálogo para empezar.</div>';document.querySelector('#cart-summary').innerHTML=cart.length?`<div class="total"><span>Total de productos</span><strong>${money(total())}</strong></div><p>Envío pendiente de cotización. Compra de demostración, sin cobro.</p><button id="checkout" class="primary full">Revisar pedido ↗</button>`:''}
function mutate(id,delta){const p=products.find(p=>p.id===id);if(!p)return;const item=cart.find(i=>i.id===id);if((item?.qty||0)+delta>p.stock){notify('Has alcanzado la existencia disponible.');return}if(item)item.qty+=delta;else if(delta>0)cart.push({id,qty:1});cart=cart.filter(i=>i.qty>0);save('nexo-cart',cart);updateCart()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.category){category=b.dataset.category;render()}if(b.dataset.add){mutate(Number(b.dataset.add),1);notify('Bolsa actualizada')}if(b.dataset.change)mutate(Number(b.dataset.change),Number(b.dataset.delta));if(b.dataset.remove){cart=cart.filter(i=>i.id!==Number(b.dataset.remove));save('nexo-cart',cart);updateCart()}if(b.classList.contains('close'))b.closest('dialog').close();if(b.id==='checkout'){document.querySelector('#cart-dialog').close();document.querySelector('#checkout-summary').innerHTML=`<p>${cart.reduce((s,i)=>s+i.qty,0)} artículo(s)</p><div class="total"><span>Total de productos</span><strong>${money(total())}</strong></div><p>Inventario simulado · Sin envío ni pago real.</p>`;document.querySelector('#checkout-dialog').showModal()}});
document.querySelector('#search').addEventListener('input',render);document.querySelector('#sort').addEventListener('change',render);
document.querySelector('#cart-button').onclick=()=>{updateCart();document.querySelector('#cart-dialog').showModal()};
function showOrders(){const el=document.querySelector('#orders-list');el.replaceChildren();if(!orders.length){el.innerHTML='<p class="empty">Todavía no tienes pedidos de demostración.</p>'}else orders.slice().reverse().forEach(o=>{const row=document.createElement('div');row.className='order';const title=document.createElement('strong');title.textContent=o.id;const detail=document.createElement('p');detail.textContent=`${new Date(o.date).toLocaleString('es-CR')} · ${money(o.total)}`;const items=document.createElement('p');items.textContent=Array.isArray(o.items)?o.items.map(i=>`${i.qty} × ${products.find(p=>p.id===i.id)?.name||'Producto'}`).join(', '):'';const status=document.createElement('small');status.textContent='Registrado en este navegador · Demostración';row.append(title,detail,items,status);el.append(row)});document.querySelector('#orders-dialog').showModal()}
document.querySelector('#orders-button').onclick=showOrders;
document.querySelector('#confirm-order').onclick=()=>{if(!cart.length)return;const order={id:`NX-${Date.now().toString(36).toUpperCase()}`,date:new Date().toISOString(),items:cart.map(i=>({...i})),total:total()};if(!save('nexo-orders',[...orders,order]))return;orders.push(order);cart=[];save('nexo-cart',cart);updateCart();document.querySelector('#checkout-dialog').close();showOrders();notify('Pedido de demostración creado')};
render();updateCart();
