<!doctype html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATELIER — Tecnología con carácter</title><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="premium.css"></head>
<body>
<div class="announcement">TECNOLOGÍA, CON OTRA PERSPECTIVA. <span>COSTA RICA / EST. 2026</span></div>
<header><a class="logo" href="./">AspendTecnology<span>TECH COLLECTION</span></a><nav><a href="#catalogo">La colección</a><a href="#como-funciona">La experiencia</a><button class="text-button" id="orders-button">Mis pedidos</button></nav><button id="cart-button" class="cart-button">Bolsa <span id="cart-count">0</span> ↗</button></header>
<main>
<section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span> THE TECHNOLOGY EDIT — 2026</div><h1>Lo extraordinario.<br><em>Todos los días.</em></h1><p>Objetos que inspiran. Tecnología que transforma tu espacio. Una selección para quienes aprecian cada detalle.</p><a class="primary" href="#catalogo">Explorar la colección <span>↗</span></a><div class="hero-note">DISEÑO CON INTENCIÓN. TECNOLOGÍA CON CARÁCTER.</div></div><div class="hero-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-caption">LA FORMA SIGUE A LA INSPIRACIÓN.</div><div class="laptop"><div class="screen"><div class="screen-orb"></div><div class="screen-text">Beyond<br>the <i>ordinary.</i></div></div><div class="keyboard"></div></div><div class="floating-tag"><span>↗</span><div>El arte de crear<small>Una nueva perspectiva</small></div></div><div class="art-footer">LA EDICIÓN ATELIER <span>VOL. 01 — 2026</span></div></div></section>
<section class="benefits"><div><b>↗</b><span>Hasta tu puerta<small>Envíos a todo Costa Rica</small></span></div><div><b>◇</b><span>Compra con claridad<small>Precios y disponibilidad visibles</small></span></div><div><b>◎</b><span>Siempre conectado<small>Seguimiento de tus pedidos</small></span></div><div><b>✧</b><span>Tecnología para ti<small>Equipos para cada momento</small></span></div></section>
<section id="catalogo" class="catalog"><div class="section-heading"><div><div class="eyebrow">LA COLECCIÓN</div><h2>Elegidos con intención.</h2></div><span id="result-count"></span></div><div class="catalog-toolbar"><div class="filters" aria-label="Categorías"></div><div class="search-wrap"><input id="search" type="search" placeholder="Buscar productos…" aria-label="Buscar productos"><span>⌕</span></div><select id="sort" aria-label="Ordenar productos"><option value="featured">Destacados</option><option value="asc">Menor precio</option><option value="desc">Mayor precio</option></select></div><div class="demo-notice"><span>◉</span> Catálogo de demostración · Los productos, precios y existencias son ilustrativos.</div><div id="products" class="products"></div></section>
<section class="process" id="como-funciona"><div><div class="eyebrow">LA EXPERIENCIA ATELIER</div><h2>Cada detalle.<br><em>De principio a fin.</em></h2><p>Una experiencia de compra pensada para acompañarte de principio a fin.</p></div><ol><li><span>01</span><div><h3>Encuentra tu equipo</h3><p>Explora el catálogo y agrega tus favoritos a la bolsa.</p></div></li><li><span>02</span><div><h3>Confirma tu pedido</h3><p>Revisa tus productos y el total antes de continuar.</p></div></li><li><span>03</span><div><h3>Recíbelo en casa</h3><p>El flujo previsto conecta el despacho de Eurocom con el transporte de Rapedido. Plazos sujetos a confirmación.</p></div></li></ol></section>
</main><footer><a class="logo" href="./">ATELIER<span>TECH COLLECTION</span></a><p>Tecnología con carácter.</p><small>Prototipo · Sin pagos ni envíos reales</small></footer>
<dialog id="cart-dialog"><div class="dialog-heading"><h2>Tu bolsa <span>↗</span></h2><button class="close" aria-label="Cerrar">×</button></div><div id="cart-items"></div><div id="cart-summary"></div></dialog>
<dialog id="checkout-dialog"><div class="dialog-heading"><h2>Confirmar pedido</h2><button class="close" aria-label="Cerrar">×</button></div><p>Este pedido es una prueba guardada únicamente en este navegador. No se cobra ni se envía a Eurocom.</p><div id="checkout-summary"></div><button class="primary full" id="confirm-order">Crear pedido de demostración ↗</button></dialog>
<dialog id="orders-dialog"><div class="dialog-heading"><h2>Mis pedidos</h2><button class="close" aria-label="Cerrar">×</button></div><div id="orders-list"></div></dialog><div id="toast" role="status"></div><script src="app.js"></script>
</body></html>
