<script setup lang="ts">
import { useForm, router } from '@inertiajs/vue3';
import { watch, ref } from 'vue';
import type { CatalogImage } from '../types/catalog';
const props = defineProps<{ productId: number; images: CatalogImage[]; canManage: boolean }>();
const order = useForm({ images: [] as { id: number; alt: string }[], primary_id: null as number | null });
watch(() => props.images, images => { order.images = images.map(i => ({ id: i.id, alt: i.alt })); order.primary_id = images.find(i => i.is_primary)?.id ?? null; }, { immediate: true, deep: true });
const upload = useForm({ files: [] as File[], alt: '' }); const fileInput = ref<HTMLInputElement | null>(null);
const errors = ref<string[]>([]);
function move(index: number, direction: number) { const next = index + direction; if (next < 0 || next >= order.images.length) return; [order.images[index], order.images[next]] = [order.images[next], order.images[index]]; }
function archive(id: number) { if (!window.confirm('¿Retirar esta imagen? Se conservarán el archivo y el registro.')) return; router.delete(`/admin/catalog/products/${props.productId}/images/${id}`, { preserveScroll: true, onError: e => { errors.value = Object.values(e); } }); }
function add() { upload.post(`/admin/catalog/products/${props.productId}/images`, { preserveScroll: true, forceFormData: true, onSuccess: () => { upload.reset(); if (fileInput.value) fileInput.value.value = ''; } }); }
</script>
<template><section class="info-card compact-form"><h2>Imágenes del producto</h2><p class="muted">JPG, PNG o WebP. Hasta 5 MB y 4096 × 4096 por archivo; máximo 12 imágenes. La primera será principal.</p><form v-if="canManage" @submit.prevent="add"><label>Archivos<input ref="fileInput" type="file" accept="image/jpeg,image/png,image/webp" multiple required @change="upload.files = Array.from(($event.target as HTMLInputElement).files ?? [])"></label><label>Texto alternativo inicial<input v-model="upload.alt" required maxlength="180"></label><p v-for="(error, key) in upload.errors" :key="key" class="field-error" role="alert">{{ error }}</p><button class="button mt-4" :disabled="upload.processing">Subir imágenes</button></form><form v-if="order.images.length" @submit.prevent="order.patch(`/admin/catalog/products/${productId}/images`, { preserveScroll: true })"><div v-for="(image, index) in order.images" :key="image.id" class="image-editor-row"><img :src="`/catalog-images/${image.id}`" :alt="image.alt" loading="lazy"><div><label>Texto alternativo<input v-model="image.alt" :disabled="!canManage" required maxlength="180"></label><label class="inline-choice"><input v-model="order.primary_id" type="radio" :value="image.id" :disabled="!canManage"> Principal</label><div v-if="canManage" class="catalog-toolbar"><button type="button" :disabled="index === 0" @click="move(index, -1)" aria-label="Mover imagen antes">↑</button><button type="button" :disabled="index === order.images.length - 1" @click="move(index, 1)" aria-label="Mover imagen después">↓</button><button type="button" class="quiet-link" @click="archive(image.id)">Retirar</button></div></div></div><p v-for="(error, key) in order.errors" :key="key" class="field-error" role="alert">{{ error }}</p><button v-if="canManage" class="button" :disabled="order.processing">Guardar orden y textos</button></form><p v-else class="muted">Sin imágenes.</p><p v-for="error in errors" :key="error" class="field-error" role="alert">{{ error }}</p></section></template>
