<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { ref } from 'vue';
import AccountLayout from '../../../layouts/AccountLayout.vue';
import { money, statusLabel, type Paginator, type Product } from '../../../types/catalog';
const props = defineProps<{ products: Paginator<Product>; filters: { q?: string; status?: string }; canManage: boolean }>();
const q = ref(props.filters.q ?? ''); const status = ref(props.filters.status ?? '');
const search = () => router.get('/admin/catalog/products', { q: q.value, status: status.value }, { preserveState: true });
</script>
<template><Head title="Productos"/><AccountLayout title="Catálogo comercial" section="admin"><div class="catalog-toolbar"><p class="muted">{{ products.total }} productos · {{ canManage ? 'Administración' : 'Solo consulta' }}</p><Link v-if="canManage" href="/admin/catalog/products/create" class="button">Crear producto ↗</Link><Link href="/catalog" class="quiet-link">Vista pública</Link></div><form class="catalog-filters compact-form" @submit.prevent="search"><input v-model="q" placeholder="Nombre o SKU" aria-label="Buscar por nombre o SKU"><select v-model="status" aria-label="Estado"><option value="">Todos los estados</option><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select><button class="button">Buscar</button></form><div class="table-wrap"><table><thead><tr><th>Producto</th><th>SKU</th><th>Precio</th><th>Estado</th><th>Acción</th></tr></thead><tbody><tr v-for="product in products.data" :key="product.id"><td>{{ product.name }}<small class="block muted">{{ product.category?.name }} · {{ product.is_demo ? 'Demostración' : product.brand?.name }}</small></td><td>{{ product.sku }}</td><td>{{ money(product.price_minor, product.currency) }}</td><td>{{ statusLabel(product.status) }}</td><td><Link :href="`/admin/catalog/products/${product.id}/edit`" class="quiet-link">{{ canManage ? 'Editar' : 'Consultar' }}</Link></td></tr><tr v-if="!products.data.length"><td colspan="5">No hay productos que coincidan.</td></tr></tbody></table></div><nav class="pagination"><Link v-if="products.prev_page_url" :href="products.prev_page_url">← Anterior</Link><span>Página {{ products.current_page }}</span><Link v-if="products.next_page_url" :href="products.next_page_url">Siguiente →</Link></nav></AccountLayout></template>
