<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';
import { nextTick, ref } from 'vue';
import AccountLayout from '../../../layouts/AccountLayout.vue';
import CommercialErrors from '../../../components/CommercialErrors.vue';
interface Rule { id:number; name:string; multiplier:string }
defineProps<{ rules:Rule[]; categories:{id:number;name:string;parent_id:number|null;status:string}[];assignments:{category_id:number;pricing_rule_id:number}[];canManage:boolean }>();
const selected=ref<number|null>(null),form=useForm({name:'',multiplier:''});
const assign=useForm({category_id:'' as number|string,pricing_rule_id:null as number|null});
function edit(rule:Rule){selected.value=rule.id;form.name=rule.name;form.multiplier=rule.multiplier;document.getElementById('rule-name')?.focus();}
function save(){const options={onError:()=>nextTick(()=>document.getElementById('rule-errors')?.focus())};if(selected.value)form.put(`/admin/commercial/rules/${selected.value}`,options);else form.post('/admin/commercial/rules',options);}
function saveAssignment(){assign.put('/admin/commercial/category-rule',{onError:()=>nextTick(()=>document.getElementById('assignment-errors')?.focus())});}
</script>
<template><Head title="Reglas comerciales"><meta name="robots" content="noindex, nofollow"/></Head><AccountLayout title="Reglas comerciales" section="admin"><p>Son multiplicadores sobre el costo, no porcentajes de margen. No cambian el precio público automáticamente.</p><p class="muted">Prioridad: excepción del producto → regla de la categoría más cercana. Sin regla, no se propone un precio.</p><div class="commercial-cards"><article v-for="rule in rules" :key="rule.id" class="info-card"><h2>{{ rule.name }}</h2><p class="commercial-number">× {{ rule.multiplier }}</p><button v-if="canManage" class="quiet-link" @click="edit(rule)">Editar {{ rule.name }}</button></article></div><form v-if="canManage" class="info-card compact-form" @submit.prevent="save"><h2>{{ selected ? 'Editar regla' : 'Nueva regla' }}</h2><fieldset :disabled="form.processing"><label for="rule-name">Nombre<input id="rule-name" v-model="form.name" required maxlength="120"></label><label>Multiplicador<input v-model="form.multiplier" inputmode="decimal" required maxlength="8" placeholder="1.4000" :aria-invalid="!!form.errors.multiplier" aria-describedby="rule-errors-multiplier"></label><CommercialErrors :errors="form.errors" prefix="rule-errors"/><button class="button">Guardar regla</button><button type="button" class="quiet-link" @click="selected=null;form.reset()">Nueva regla</button></fieldset></form><section class="info-card"><h2>Asignaciones por categoría</h2><ul><li v-for="mapping in assignments" :key="mapping.category_id">{{ categories.find(c=>c.id===mapping.category_id)?.name }} → {{ rules.find(r=>r.id===mapping.pricing_rule_id)?.name }}</li></ul><form v-if="canManage" class="compact-form" @submit.prevent="saveAssignment"><fieldset :disabled="assign.processing"><label>Categoría<select v-model="assign.category_id" required><option value="" disabled>Seleccionar categoría</option><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select></label><label>Regla<select v-model="assign.pricing_rule_id"><option :value="null">Sin regla propia / heredar</option><option v-for="rule in rules" :key="rule.id" :value="rule.id">{{ rule.name }} × {{ rule.multiplier }}</option></select></label><CommercialErrors :errors="assign.errors" prefix="assignment-errors"/><button class="button">Guardar asignación</button></fieldset></form></section></AccountLayout></template>
