<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';
import { nextTick } from 'vue';
import AccountLayout from '../../../layouts/AccountLayout.vue';
import CommercialErrors from '../../../components/CommercialErrors.vue';
import { money, type Paginator } from '../../../types/catalog';
import { availabilityLabel, type Supplier, type SupplierOffer } from '../../../types/commercial';
const props=defineProps<{ supplier: Supplier; offers: Paginator<SupplierOffer>; canManage: boolean }>();
const form=useForm({name:props.supplier.name,code:props.supplier.code,active:props.supplier.active,notes:props.supplier.notes??''});
const save=()=>form.put(`/admin/commercial/suppliers/${props.supplier.id}`,{onError:()=>nextTick(()=>document.getElementById('supplier-errors')?.focus())});
</script>
<template><Head :title="supplier.name"><meta name="robots" content="noindex, nofollow"/></Head><AccountLayout :title="supplier.name" section="admin"><Link href="/admin/commercial/suppliers">← Proveedores</Link><form class="info-card compact-form" @submit.prevent="save"><fieldset :disabled="!canManage || form.processing"><label>Nombre<input v-model="form.name" required maxlength="120"></label><label>Código interno<input v-model="form.code" required maxlength="60"></label><label>Notas privadas<textarea v-model="form.notes" maxlength="2000"/></label><label class="inline-choice"><input v-model="form.active" type="checkbox"> Proveedor activo</label><CommercialErrors :errors="form.errors" prefix="supplier-errors"/><button v-if="canManage" class="button">Actualizar proveedor</button></fieldset></form><h2>Ofertas vinculadas</h2><p>La información se registra manualmente; no representa inventario en tiempo real.</p><p v-if="!offers.data.length" class="notice">Sin ofertas. Abre un producto del catálogo administrativo para asociar su SKU y datos confirmados.</p><Link href="/admin/catalog/products" class="button">Abrir productos</Link><article v-for="offer in offers.data" :key="offer.id" class="info-card"><h3><Link :href="`/admin/commercial/products/${offer.product_id}`">{{ offer.product?.name }}</Link></h3><p v-if="offer.product?.is_demo" class="notice">Producto DEMO</p><p>SKU proveedor: {{ offer.supplier_sku }}</p><p>Costo: {{ offer.cost_minor === null ? 'No confirmado' : money(offer.cost_minor,offer.currency) }}</p><p>{{ availabilityLabel(offer.availability) }} · Stock: {{ offer.stock ?? 'Desconocido' }} · {{ offer.active ? 'Activa' : 'Inactiva' }}</p><p>Observado: {{ new Date(offer.observed_at).toLocaleString('es-CR') }}</p></article><nav aria-label="Páginas de ofertas"><Link v-if="offers.prev_page_url" :href="offers.prev_page_url">Anterior</Link> <Link v-if="offers.next_page_url" :href="offers.next_page_url">Siguiente</Link></nav></AccountLayout></template>
